"""wework

Revision ID: 2809fbbf08bc
Revises: c1b794a961ce
Create Date: 2025-11-17 14:48:10.965213

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2809fbbf08bc'
down_revision = 'c1b794a961ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('wework_userid', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'wework_userid')
    # ### end Alembic commands ###
